[project]
name = "tg_core"
version = "0.1.0"
description = "Telegram core shared infrastructure (rate limiting, gateway, logging, config, domain primitives)"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "S16", email = "dev@example.com" }]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tg_core", "tg_core.infra", "tg_core.domain", "tg_core.config"]
